apiVersion: batch/v1
kind: Job
metadata:
  name: rsync
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: rsync
    spec:
      containers:
        - name: rsync
          image: alpine:latest
          command: ["apk"]
          args: ["add", "rsync"]
          volumeMounts:
            - name: source
              mountPath: /srcd
            - name: destination
              mountPath: /dest
      restartPolicy: OnFailure
      volumes:
        - name: source
          persistentVolumeClaim:
            claimName: ${SOURCE_PVC}
        - name: destination
          persistentVolumeClaim:
            claimName: ${DEST_PVC}
