apiVersion: batch/v1
kind: Job
metadata:
  name: rsync
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: rsync
    spec:
      containers:
        - name: rsync
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - apk add rsync;
              rsync ${RSYNC_OPTS:-"-apvH"} /srcd/ /dest/
          volumeMounts:
            - name: source
              mountPath: /srcd
            - name: destination
              mountPath: /dest
      restartPolicy: OnFailure
      volumes:
        - name: source
          persistentVolumeClaim:
            claimName: ${SRC_PVC}
        - name: destination
          persistentVolumeClaim:
            claimName: ${DST_PVC}
