apiVersion: v1
kind: Pod
metadata:
  name: rsync
spec:
  containers:
    - name: rsync
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args:
        - apk add rsync;
          while true; do sleep 30; done;
      volumeMounts:
        - name: source
          mountPath: /srcd
        - name: destination
          mountPath: /dest
  restartPolicy: OnFailure
  volumes:
    - name: source
      persistentVolumeClaim:
        claimName: ${SRC_PVC}
    - name: destination
      persistentVolumeClaim:
        claimName: ${DST_PVC}
