apiVersion: v1
kind: Pod
metadata:
  name: rsync
spec:
  containers:
    - name: rsync
      image: alpine:latest
      command: ['apk', 'add', 'rsync']
      volumeMounts:
        - name: source
          mountPath: /srcd
        - name: destination
          mountPath: /dest
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh"]
  restartPolicy: OnFailure
  volumes:
    - name: source
      persistentVolumeClaim:
        claimName: ${SRC_PVC}
    - name: destination
      persistentVolumeClaim:
        claimName: ${DST_PVC}
